[build]
  publish = "."
  command = ""

[[redirects]]
  from = "https://xn--deingeschftskompass-owb.de/*"
  to = "https://deingeschaeftskompass.de/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/blog/:slug"
  to = "/blog/:slug.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"